name: Windows11 QEMU noVNC Secure

on:
  workflow_dispatch:

jobs:
  win11-vm:
    runs-on: ubuntu-silm

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v31.9.1
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Install QEMU and noVNC
        run: |
          nix profile install nixpkgs#qemu
          nix profile install nixpkgs#novnc

      - name: Create VNC password file
        run: |
          echo "${{ secrets.VNC_PASSWORD }}" | vncpasswd -f > passwd
          chmod 600 passwd

      - name: Download Windows 11 ISO
        run: |
          mkdir -p iso
          wget -O iso/Win11.iso "https://dw.softmany.net/aHR0cHM6Ly9hcmNoaXZlLm9yZy9kb3dubG9hZC9XMTF4NjRfMjYyMDAuNjU4NC8yNjIwMC42NTg0LjI1MDkxNS0xOTA1LjI1aDJfZ2VfcmVsZWFzZV9zdmNfcmVmcmVzaF9DTElFTlRfQ09OU1VNRVJfeDY0RlJFX2VuLXVzLmlzbw=="

      - name: Create disk
        run: |
          qemu-img create -f qcow2 win11.img 50G

      - name: Start Windows 11 VM
        run: |
          qemu-system-x86_64 \
            -m 8192 \
            -smp 4 \
            -enable-kvm \
            -cpu host \
            -machine type=q35,accel=kvm \
            -drive file=win11.img,format=qcow2 \
            -cdrom iso/Win11.iso \
            -boot d \
            -vga virtio \
            -net nic -net user \
            -usb -device usb-tablet \
            -vnc 0.0.0.0:1,password=on \
            -monitor none \
            -daemonize

      - name: Start noVNC (public port 6080)
        run: |
          novnc_server \
            --vnc localhost:5901 \
            --listen 0.0.0.0:6080
